//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatConverter.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormatConverter.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload modules.
        /// </summary>
        public static string AdminModulesOptionTitle {
            get {
                return ResourceManager.GetString("AdminModulesOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user permissions.
        /// </summary>
        public static string AdminPermissionsOptionTitle {
            get {
                return ResourceManager.GetString("AdminPermissionsOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a user.
        /// </summary>
        public static string AdminUserRegistrationTitle {
            get {
                return ResourceManager.GetString("AdminUserRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any of the permitted formats.
        /// </summary>
        public static string ConversionInferenceName {
            get {
                return ResourceManager.GetString("ConversionInferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRSU.
        /// </summary>
        public static string ConversionTargetFormat {
            get {
                return ResourceManager.GetString("ConversionTargetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is taken..
        /// </summary>
        public static string EmailTakenWarningMessage {
            get {
                return ResourceManager.GetString("EmailTakenWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source file format. Please, make sure its in the correct format before uploading..
        /// </summary>
        public static string InvalidFormatWarningMessage {
            get {
                return ResourceManager.GetString("InvalidFormatWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either email or password is wrong..
        /// </summary>
        public static string LoginFailedWarningMessage {
            get {
                return ResourceManager.GetString("LoginFailedWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given module is already uploaded..
        /// </summary>
        public static string ModuleExistenceWarningMessage {
            get {
                return ResourceManager.GetString("ModuleExistenceWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules are libraries that have &apos;.dll&apos; extension. Please, make sure of it and try again..
        /// </summary>
        public static string ModuleFileWarningMessage {
            get {
                return ResourceManager.GetString("ModuleFileWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the given email does not exist..
        /// </summary>
        public static string NonexistentEmailWarningMessage {
            get {
                return ResourceManager.GetString("NonexistentEmailWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string PasswordConfirmationName {
            get {
                return ResourceManager.GetString("PasswordConfirmationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string PasswordLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordMismatchErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMismatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please, try again later..
        /// </summary>
        public static string UnknownErrorWarningMessage {
            get {
                return ResourceManager.GetString("UnknownErrorWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a .zip format file..
        /// </summary>
        public static string ZipFileWarningMessage {
            get {
                return ResourceManager.GetString("ZipFileWarningMessage", resourceCulture);
            }
        }
    }
}
